### ISSUE TITLE
Bug in SphericalTensor.invarant()

### ISSUE THREAD

**Issue by X1X1010** [zrqiao/torch-gauge#1]
We found a NotImplementedError when running OrbNet2, reproducing results you provided at Zendo. The error occurred at line 408 located at torch-gauge.o3.spherical.py. We think the 'if' statement at line 396 should be changed to 'elif'.

BTW, as claimed by torch_gauge, the m (magnetic quamtum number) index lies in incremental order, while  the OrbNet2 model reverse the m index order of its read-in tensors to match the torch_gauge's layout. To our understanding, this leads to a  descending order in m when data goes into the model. Can you explain why this is necessary in data preprocessing, thanks. 

Have a nice weekend!

**Comment by zrqiao** [comment]
Thank you for catching the typo. Yes, it should be elif - would be great if you can make a PR. 
I'm not entirely sure about why the bug is invoked from the zenodo code though - have you successfully reproduced the results after fixing this issue? Otherwise, I may review the network code to find potential inconsistencies.
For magnetic quantum number ordering, we assume the input basis set is of standard Gaussian format (descending m), and they are aligned to the torch_gauge convention when passed to the network.

**Comment by wjyan39** [comment]
> Thank you for catching the typo. Yes, it should be elif - would be great if you can make a PR. I'm not entirely sure about why the bug is invoked from the zenodo code though - have you successfully reproduced the results after fixing this issue? Otherwise, I may review the network code to find potential inconsistencies. For magnetic quantum number ordering, we assume the input basis set is of standard Gaussian format (descending m), and they are aligned to the torch_gauge convention when passed to the network.

Thank you for replying us so quickly :) Yes, we can run the code successfully after fixing the typo and have reproduced the results, not fully, but only one data point (QM9 U0 MAE, model @ 1024 training data size) as we've only tried this. 

Speaking to the magnetic quantum number ordering, to our experience, the majority of Quamtum Chemistry Programs treat p orbitals in x, y, z laying form, which corresponds to m<0, m>0 and m=0 respectively (to my understanding). And for d and f type orbitals, the m index goes in incremental order, i.e. ranging from -l to l. So, is there any difference in Qcore's treatment of this ordering, as we do not know how to tell QCore to provide the needed integrals or QC matrices. 

To my personal understanding, the reverse in m ordering trick is somehow to match the CG coefficient's layout in torch_gauge's
CG couplers, the m ordering of torch_gauge's CGs seems having been changed ( to the descending order) via transforms, though l'm not quite sure. 

Anyway, thank you again :)

**Comment by zrqiao** [comment]
That's great to hear!

For Gaussian basis format used in our calculations (as can be found on BasisSetExchange), I recall the p orbital ordering was (y, z, x). I assume basis ordering within torch_gauge itself is supposed to be self-consistent, although it would take me some work to reparse the implementation details I made in 2021.

**Comment by jeanwsr** [comment]
> For Gaussian basis format used in our calculations (as can be found on BasisSetExchange)

No, the information provided by BSE does not include the ordering of p orbitals. The ordering is determined by the convention of the quantum chemical program (more specifically, the integral library) you use. 

And I'm pretty sure that the ordering of Gaussian is (x,y,z). Also, there's probably no such a program using (y,z,x) in the world.

**Comment by zrqiao** [comment]
@hebrewsnabla That makes sense. In case that's helpful, the integral engine we used was intception which itself is a wrapper of libcint.

**Comment by jeanwsr** [comment]
Thanks your information. libcint uses (x,y,z) ordering, which I'm also pretty sure.
